services:
  - type: web
    name: itda-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: SEED_SAMPLE_DATA
        value: "true"
      - key: FLASK_DEBUG
        value: "false"
      - key: SESSION_COOKIE_SAMESITE
        value: "None"
      - key: SESSION_COOKIE_SECURE
        value: "true"
